#!/usr/bin/perl -w

use strict;
use warnings;
use lib 'lib';
use Yapess::SudokuMatrix;

my $mat = Yapess::SudokuMatrix->new;
my $path = shift or die("No input file specified - pass input file path as argument");
$mat->load($path);
$mat->solve();
$mat->print;

